language: python
python:
  - "3.7"
dist: xenial
os:
  - linux
sudo: true
virtualenv:
  system_site_packages: false
install:
  - pip install -r requirements_dev.txt
  - pip install pytest pytest-cov
script:
  - pytest tests/unit